// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD3ui0WMU3QRIgygUvvMiRK4Fec9fBBCmo',
    appId: '1:606752585136:android:03fb393f455c6fd3c35275',
    messagingSenderId: '606752585136',
    projectId: 'yamguard-e4837',
    storageBucket: 'yamguard-e4837.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBI7ba_bsHIqUQnQuKJqcbNq7HF08HplXI',
    appId: '1:606752585136:ios:445ea44413359c1cc35275',
    messagingSenderId: '606752585136',
    projectId: 'yamguard-e4837',
    storageBucket: 'yamguard-e4837.firebasestorage.app',
    iosBundleId: 'com.example.yamGuard',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAqUwz__J-9yh-KfNJMkLSVhlGnNm9VzHE',
    appId: '1:606752585136:web:de39df766ecde183c35275',
    messagingSenderId: '606752585136',
    projectId: 'yamguard-e4837',
    authDomain: 'yamguard-e4837.firebaseapp.com',
    storageBucket: 'yamguard-e4837.firebasestorage.app',
    measurementId: 'G-REN34WERTP',
  );

}